version: '3.8'
services:
  stock_service:
    image: ghcr.io/chrischivlog/broker-type:main
    container_name: stock-service
    working_dir: /app
    volumes:
      - ./app:/app
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
